# Generated by Django 2.2.13 on 2021-07-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='user',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
