# Generated by Django 2.2.13 on 2021-07-07 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210707_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='address',
        ),
    ]
