# Generated by Django 2.2.13 on 2021-07-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_personalroommessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalroommessage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='personalroommessage',
            name='links',
        ),
    ]
