# Generated by Django 2.2.13 on 2021-07-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210715_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalRoomMessage',
        ),
    ]
